//edition = "2023";

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v6.30.0
// source: middleware/hasq.proto

package hasq

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TokenCreate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenCreate) Reset() {
	*x = TokenCreate{}
	mi := &file_middleware_hasq_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenCreate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenCreate) ProtoMessage() {}

func (x *TokenCreate) ProtoReflect() protoreflect.Message {
	mi := &file_middleware_hasq_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenCreate.ProtoReflect.Descriptor instead.
func (*TokenCreate) Descriptor() ([]byte, []int) {
	return file_middleware_hasq_proto_rawDescGZIP(), []int{0}
}

func (x *TokenCreate) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TokenCreate) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type TokenReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Hash          string                 `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3,oneof" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenReply) Reset() {
	*x = TokenReply{}
	mi := &file_middleware_hasq_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenReply) ProtoMessage() {}

func (x *TokenReply) ProtoReflect() protoreflect.Message {
	mi := &file_middleware_hasq_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenReply.ProtoReflect.Descriptor instead.
func (*TokenReply) Descriptor() ([]byte, []int) {
	return file_middleware_hasq_proto_rawDescGZIP(), []int{1}
}

func (x *TokenReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TokenReply) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TokenReply) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *TokenReply) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type TokenSearch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Search:
	//
	//	*TokenSearch_Id
	//	*TokenSearch_Hash
	Search        isTokenSearch_Search `protobuf_oneof:"search"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenSearch) Reset() {
	*x = TokenSearch{}
	mi := &file_middleware_hasq_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenSearch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenSearch) ProtoMessage() {}

func (x *TokenSearch) ProtoReflect() protoreflect.Message {
	mi := &file_middleware_hasq_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenSearch.ProtoReflect.Descriptor instead.
func (*TokenSearch) Descriptor() ([]byte, []int) {
	return file_middleware_hasq_proto_rawDescGZIP(), []int{2}
}

func (x *TokenSearch) GetSearch() isTokenSearch_Search {
	if x != nil {
		return x.Search
	}
	return nil
}

func (x *TokenSearch) GetId() string {
	if x != nil {
		if x, ok := x.Search.(*TokenSearch_Id); ok {
			return x.Id
		}
	}
	return ""
}

func (x *TokenSearch) GetHash() string {
	if x != nil {
		if x, ok := x.Search.(*TokenSearch_Hash); ok {
			return x.Hash
		}
	}
	return ""
}

type isTokenSearch_Search interface {
	isTokenSearch_Search()
}

type TokenSearch_Id struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3,oneof"`
}

type TokenSearch_Hash struct {
	Hash string `protobuf:"bytes,2,opt,name=hash,proto3,oneof"`
}

func (*TokenSearch_Id) isTokenSearch_Search() {}

func (*TokenSearch_Hash) isTokenSearch_Search() {}

var File_middleware_hasq_proto protoreflect.FileDescriptor

var file_middleware_hasq_proto_rawDesc = string([]byte{
	0x0a, 0x15, 0x6d, 0x69, 0x64, 0x64, 0x6c, 0x65, 0x77, 0x61, 0x72, 0x65, 0x2f, 0x68, 0x61, 0x73,
	0x71, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x68, 0x61, 0x73, 0x71, 0x22, 0x37, 0x0a,
	0x0b, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x68, 0x0a, 0x0a, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61,
	0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x12, 0x17,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x64, 0x61, 0x74, 0x61,
	0x22, 0x3f, 0x0a, 0x0b, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12,
	0x10, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x14, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x42, 0x08, 0x0a, 0x06, 0x73, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x32, 0x71, 0x0a, 0x07, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x32, 0x0a, 0x0b,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x11, 0x2e, 0x68, 0x61,
	0x73, 0x71, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x1a, 0x10,
	0x2e, 0x68, 0x61, 0x73, 0x71, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x32, 0x0a, 0x0b, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12,
	0x11, 0x2e, 0x68, 0x61, 0x73, 0x71, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x1a, 0x10, 0x2e, 0x68, 0x61, 0x73, 0x71, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x42, 0x11, 0x5a, 0x0f, 0x6d, 0x69, 0x64, 0x64, 0x6c, 0x65, 0x77, 0x61,
	0x72, 0x65, 0x2f, 0x68, 0x61, 0x73, 0x71, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_middleware_hasq_proto_rawDescOnce sync.Once
	file_middleware_hasq_proto_rawDescData []byte
)

func file_middleware_hasq_proto_rawDescGZIP() []byte {
	file_middleware_hasq_proto_rawDescOnce.Do(func() {
		file_middleware_hasq_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_middleware_hasq_proto_rawDesc), len(file_middleware_hasq_proto_rawDesc)))
	})
	return file_middleware_hasq_proto_rawDescData
}

var file_middleware_hasq_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_middleware_hasq_proto_goTypes = []any{
	(*TokenCreate)(nil), // 0: hasq.TokenCreate
	(*TokenReply)(nil),  // 1: hasq.TokenReply
	(*TokenSearch)(nil), // 2: hasq.TokenSearch
}
var file_middleware_hasq_proto_depIdxs = []int32{
	0, // 0: hasq.Service.CreateToken:input_type -> hasq.TokenCreate
	2, // 1: hasq.Service.SearchToken:input_type -> hasq.TokenSearch
	1, // 2: hasq.Service.CreateToken:output_type -> hasq.TokenReply
	1, // 3: hasq.Service.SearchToken:output_type -> hasq.TokenReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_middleware_hasq_proto_init() }
func file_middleware_hasq_proto_init() {
	if File_middleware_hasq_proto != nil {
		return
	}
	file_middleware_hasq_proto_msgTypes[1].OneofWrappers = []any{}
	file_middleware_hasq_proto_msgTypes[2].OneofWrappers = []any{
		(*TokenSearch_Id)(nil),
		(*TokenSearch_Hash)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_middleware_hasq_proto_rawDesc), len(file_middleware_hasq_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_middleware_hasq_proto_goTypes,
		DependencyIndexes: file_middleware_hasq_proto_depIdxs,
		MessageInfos:      file_middleware_hasq_proto_msgTypes,
	}.Build()
	File_middleware_hasq_proto = out.File
	file_middleware_hasq_proto_goTypes = nil
	file_middleware_hasq_proto_depIdxs = nil
}
