CREATE DATABASE pet WITH ENCODING = "UTF-8";
\c pet;
CREATE SCHEMA class;
CREATE SCHEMA hasq;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp" SCHEMA class;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp" SCHEMA hasq;