//edition = "2023";

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: middleware/class.proto

package class

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClassStatus int32

const (
	ClassStatus_CLASS_NONE      ClassStatus = 0
	ClassStatus_CLASS_DRAFT     ClassStatus = 1
	ClassStatus_CLASS_PUBLISHED ClassStatus = 2
	ClassStatus_CLASS_ARCHIVED  ClassStatus = 3
)

// Enum value maps for ClassStatus.
var (
	ClassStatus_name = map[int32]string{
		0: "CLASS_NONE",
		1: "CLASS_DRAFT",
		2: "CLASS_PUBLISHED",
		3: "CLASS_ARCHIVED",
	}
	ClassStatus_value = map[string]int32{
		"CLASS_NONE":      0,
		"CLASS_DRAFT":     1,
		"CLASS_PUBLISHED": 2,
		"CLASS_ARCHIVED":  3,
	}
)

func (x ClassStatus) Enum() *ClassStatus {
	p := new(ClassStatus)
	*p = x
	return p
}

func (x ClassStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClassStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_middleware_class_proto_enumTypes[0].Descriptor()
}

func (ClassStatus) Type() protoreflect.EnumType {
	return &file_middleware_class_proto_enumTypes[0]
}

func (x ClassStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClassStatus.Descriptor instead.
func (ClassStatus) EnumDescriptor() ([]byte, []int) {
	return file_middleware_class_proto_rawDescGZIP(), []int{0}
}

type ClassElementStatus int32

const (
	ClassElementStatus_ITEM_NONE      ClassElementStatus = 0
	ClassElementStatus_ITEM_DRAFT     ClassElementStatus = 1
	ClassElementStatus_ITEM_PUBLISHED ClassElementStatus = 2
	ClassElementStatus_ITEM_SKIP      ClassElementStatus = 3
)

// Enum value maps for ClassElementStatus.
var (
	ClassElementStatus_name = map[int32]string{
		0: "ITEM_NONE",
		1: "ITEM_DRAFT",
		2: "ITEM_PUBLISHED",
		3: "ITEM_SKIP",
	}
	ClassElementStatus_value = map[string]int32{
		"ITEM_NONE":      0,
		"ITEM_DRAFT":     1,
		"ITEM_PUBLISHED": 2,
		"ITEM_SKIP":      3,
	}
)

func (x ClassElementStatus) Enum() *ClassElementStatus {
	p := new(ClassElementStatus)
	*p = x
	return p
}

func (x ClassElementStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClassElementStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_middleware_class_proto_enumTypes[1].Descriptor()
}

func (ClassElementStatus) Type() protoreflect.EnumType {
	return &file_middleware_class_proto_enumTypes[1]
}

func (x ClassElementStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClassElementStatus.Descriptor instead.
func (ClassElementStatus) EnumDescriptor() ([]byte, []int) {
	return file_middleware_class_proto_rawDescGZIP(), []int{1}
}

type Class struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Status        ClassStatus            `protobuf:"varint,3,opt,name=status,proto3,enum=class.ClassStatus" json:"status,omitempty"`
	Version       uint32                 `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Class) Reset() {
	*x = Class{}
	mi := &file_middleware_class_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Class) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Class) ProtoMessage() {}

func (x *Class) ProtoReflect() protoreflect.Message {
	mi := &file_middleware_class_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Class.ProtoReflect.Descriptor instead.
func (*Class) Descriptor() ([]byte, []int) {
	return file_middleware_class_proto_rawDescGZIP(), []int{0}
}

func (x *Class) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Class) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Class) GetStatus() ClassStatus {
	if x != nil {
		return x.Status
	}
	return ClassStatus_CLASS_NONE
}

func (x *Class) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type ClassRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NameFilter    *string                `protobuf:"bytes,1,opt,name=name_filter,json=nameFilter,proto3,oneof" json:"name_filter,omitempty"`
	Status        *ClassStatus           `protobuf:"varint,2,opt,name=status,proto3,enum=class.ClassStatus,oneof" json:"status,omitempty"`
	Version       *uint32                `protobuf:"varint,3,opt,name=version,proto3,oneof" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassRequest) Reset() {
	*x = ClassRequest{}
	mi := &file_middleware_class_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassRequest) ProtoMessage() {}

func (x *ClassRequest) ProtoReflect() protoreflect.Message {
	mi := &file_middleware_class_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassRequest.ProtoReflect.Descriptor instead.
func (*ClassRequest) Descriptor() ([]byte, []int) {
	return file_middleware_class_proto_rawDescGZIP(), []int{1}
}

func (x *ClassRequest) GetNameFilter() string {
	if x != nil && x.NameFilter != nil {
		return *x.NameFilter
	}
	return ""
}

func (x *ClassRequest) GetStatus() ClassStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ClassStatus_CLASS_NONE
}

func (x *ClassRequest) GetVersion() uint32 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

type ClassReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Classes       []*Class               `protobuf:"bytes,1,rep,name=classes,proto3" json:"classes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassReply) Reset() {
	*x = ClassReply{}
	mi := &file_middleware_class_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassReply) ProtoMessage() {}

func (x *ClassReply) ProtoReflect() protoreflect.Message {
	mi := &file_middleware_class_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassReply.ProtoReflect.Descriptor instead.
func (*ClassReply) Descriptor() ([]byte, []int) {
	return file_middleware_class_proto_rawDescGZIP(), []int{2}
}

func (x *ClassReply) GetClasses() []*Class {
	if x != nil {
		return x.Classes
	}
	return nil
}

type ClassElement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Version       uint32                 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Status        ClassElementStatus     `protobuf:"varint,4,opt,name=status,proto3,enum=class.ClassElementStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassElement) Reset() {
	*x = ClassElement{}
	mi := &file_middleware_class_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassElement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassElement) ProtoMessage() {}

func (x *ClassElement) ProtoReflect() protoreflect.Message {
	mi := &file_middleware_class_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassElement.ProtoReflect.Descriptor instead.
func (*ClassElement) Descriptor() ([]byte, []int) {
	return file_middleware_class_proto_rawDescGZIP(), []int{3}
}

func (x *ClassElement) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ClassElement) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ClassElement) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ClassElement) GetStatus() ClassElementStatus {
	if x != nil {
		return x.Status
	}
	return ClassElementStatus_ITEM_NONE
}

type ClassElementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       *uint32                `protobuf:"varint,2,opt,name=version,proto3,oneof" json:"version,omitempty"`
	Status        *ClassElementStatus    `protobuf:"varint,3,opt,name=status,proto3,enum=class.ClassElementStatus,oneof" json:"status,omitempty"`
	Offset        *uint32                `protobuf:"varint,4,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	Limit         *uint32                `protobuf:"varint,5,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassElementRequest) Reset() {
	*x = ClassElementRequest{}
	mi := &file_middleware_class_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassElementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassElementRequest) ProtoMessage() {}

func (x *ClassElementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_middleware_class_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassElementRequest.ProtoReflect.Descriptor instead.
func (*ClassElementRequest) Descriptor() ([]byte, []int) {
	return file_middleware_class_proto_rawDescGZIP(), []int{4}
}

func (x *ClassElementRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClassElementRequest) GetVersion() uint32 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

func (x *ClassElementRequest) GetStatus() ClassElementStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ClassElementStatus_ITEM_NONE
}

func (x *ClassElementRequest) GetOffset() uint32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *ClassElementRequest) GetLimit() uint32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

type ClassElementReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Elements      []*ClassElement        `protobuf:"bytes,2,rep,name=elements,proto3" json:"elements,omitempty"`
	NextOffset    uint32                 `protobuf:"varint,3,opt,name=next_offset,json=nextOffset,proto3" json:"next_offset,omitempty"`
	Eof           bool                   `protobuf:"varint,4,opt,name=eof,proto3" json:"eof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassElementReply) Reset() {
	*x = ClassElementReply{}
	mi := &file_middleware_class_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassElementReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassElementReply) ProtoMessage() {}

func (x *ClassElementReply) ProtoReflect() protoreflect.Message {
	mi := &file_middleware_class_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassElementReply.ProtoReflect.Descriptor instead.
func (*ClassElementReply) Descriptor() ([]byte, []int) {
	return file_middleware_class_proto_rawDescGZIP(), []int{5}
}

func (x *ClassElementReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClassElementReply) GetElements() []*ClassElement {
	if x != nil {
		return x.Elements
	}
	return nil
}

func (x *ClassElementReply) GetNextOffset() uint32 {
	if x != nil {
		return x.NextOffset
	}
	return 0
}

func (x *ClassElementReply) GetEof() bool {
	if x != nil {
		return x.Eof
	}
	return false
}

var File_middleware_class_proto protoreflect.FileDescriptor

const file_middleware_class_proto_rawDesc = "" +
	"\n" +
	"\x16middleware/class.proto\x12\x05class\"w\n" +
	"\x05Class\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12*\n" +
	"\x06status\x18\x03 \x01(\x0e2\x12.class.ClassStatusR\x06status\x12\x18\n" +
	"\aversion\x18\x04 \x01(\rR\aversion\"\xab\x01\n" +
	"\fClassRequest\x12$\n" +
	"\vname_filter\x18\x01 \x01(\tH\x00R\n" +
	"nameFilter\x88\x01\x01\x12/\n" +
	"\x06status\x18\x02 \x01(\x0e2\x12.class.ClassStatusH\x01R\x06status\x88\x01\x01\x12\x1d\n" +
	"\aversion\x18\x03 \x01(\rH\x02R\aversion\x88\x01\x01B\x0e\n" +
	"\f_name_filterB\t\n" +
	"\a_statusB\n" +
	"\n" +
	"\b_version\"4\n" +
	"\n" +
	"ClassReply\x12&\n" +
	"\aclasses\x18\x01 \x03(\v2\f.class.ClassR\aclasses\"\x83\x01\n" +
	"\fClassElement\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x18\n" +
	"\aversion\x18\x03 \x01(\rR\aversion\x121\n" +
	"\x06status\x18\x04 \x01(\x0e2\x19.class.ClassElementStatusR\x06status\"\xe4\x01\n" +
	"\x13ClassElementRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\aversion\x18\x02 \x01(\rH\x00R\aversion\x88\x01\x01\x126\n" +
	"\x06status\x18\x03 \x01(\x0e2\x19.class.ClassElementStatusH\x01R\x06status\x88\x01\x01\x12\x1b\n" +
	"\x06offset\x18\x04 \x01(\rH\x02R\x06offset\x88\x01\x01\x12\x19\n" +
	"\x05limit\x18\x05 \x01(\rH\x03R\x05limit\x88\x01\x01B\n" +
	"\n" +
	"\b_versionB\t\n" +
	"\a_statusB\t\n" +
	"\a_offsetB\b\n" +
	"\x06_limit\"\x8b\x01\n" +
	"\x11ClassElementReply\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12/\n" +
	"\belements\x18\x02 \x03(\v2\x13.class.ClassElementR\belements\x12\x1f\n" +
	"\vnext_offset\x18\x03 \x01(\rR\n" +
	"nextOffset\x12\x10\n" +
	"\x03eof\x18\x04 \x01(\bR\x03eof*W\n" +
	"\vClassStatus\x12\x0e\n" +
	"\n" +
	"CLASS_NONE\x10\x00\x12\x0f\n" +
	"\vCLASS_DRAFT\x10\x01\x12\x13\n" +
	"\x0fCLASS_PUBLISHED\x10\x02\x12\x12\n" +
	"\x0eCLASS_ARCHIVED\x10\x03*V\n" +
	"\x12ClassElementStatus\x12\r\n" +
	"\tITEM_NONE\x10\x00\x12\x0e\n" +
	"\n" +
	"ITEM_DRAFT\x10\x01\x12\x12\n" +
	"\x0eITEM_PUBLISHED\x10\x02\x12\r\n" +
	"\tITEM_SKIP\x10\x032~\n" +
	"\aService\x121\n" +
	"\aClasses\x12\x13.class.ClassRequest\x1a\x11.class.ClassReply\x12@\n" +
	"\bElements\x12\x1a.class.ClassElementRequest\x1a\x18.class.ClassElementReplyB\x12Z\x10middleware/classb\x06proto3"

var (
	file_middleware_class_proto_rawDescOnce sync.Once
	file_middleware_class_proto_rawDescData []byte
)

func file_middleware_class_proto_rawDescGZIP() []byte {
	file_middleware_class_proto_rawDescOnce.Do(func() {
		file_middleware_class_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_middleware_class_proto_rawDesc), len(file_middleware_class_proto_rawDesc)))
	})
	return file_middleware_class_proto_rawDescData
}

var file_middleware_class_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_middleware_class_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_middleware_class_proto_goTypes = []any{
	(ClassStatus)(0),            // 0: class.ClassStatus
	(ClassElementStatus)(0),     // 1: class.ClassElementStatus
	(*Class)(nil),               // 2: class.Class
	(*ClassRequest)(nil),        // 3: class.ClassRequest
	(*ClassReply)(nil),          // 4: class.ClassReply
	(*ClassElement)(nil),        // 5: class.ClassElement
	(*ClassElementRequest)(nil), // 6: class.ClassElementRequest
	(*ClassElementReply)(nil),   // 7: class.ClassElementReply
}
var file_middleware_class_proto_depIdxs = []int32{
	0, // 0: class.Class.status:type_name -> class.ClassStatus
	0, // 1: class.ClassRequest.status:type_name -> class.ClassStatus
	2, // 2: class.ClassReply.classes:type_name -> class.Class
	1, // 3: class.ClassElement.status:type_name -> class.ClassElementStatus
	1, // 4: class.ClassElementRequest.status:type_name -> class.ClassElementStatus
	5, // 5: class.ClassElementReply.elements:type_name -> class.ClassElement
	3, // 6: class.Service.Classes:input_type -> class.ClassRequest
	6, // 7: class.Service.Elements:input_type -> class.ClassElementRequest
	4, // 8: class.Service.Classes:output_type -> class.ClassReply
	7, // 9: class.Service.Elements:output_type -> class.ClassElementReply
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_middleware_class_proto_init() }
func file_middleware_class_proto_init() {
	if File_middleware_class_proto != nil {
		return
	}
	file_middleware_class_proto_msgTypes[1].OneofWrappers = []any{}
	file_middleware_class_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_middleware_class_proto_rawDesc), len(file_middleware_class_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_middleware_class_proto_goTypes,
		DependencyIndexes: file_middleware_class_proto_depIdxs,
		EnumInfos:         file_middleware_class_proto_enumTypes,
		MessageInfos:      file_middleware_class_proto_msgTypes,
	}.Build()
	File_middleware_class_proto = out.File
	file_middleware_class_proto_goTypes = nil
	file_middleware_class_proto_depIdxs = nil
}
